### ISSUE TITLE
Hellies from me ( but something is wrong)

### ISSUE THREAD

**Issue by ghost** [BlackArch/blackarch-artwork#7]
I am an Hacktivist and thought about using Blackarch 
I found a picture (bluhd-lion.png )
Its very cool but ironic
Its inderectly saying that BlackArch is a Linux for freedom ... but BlackArch seems to be a repo For arch and so just different than it looks.....

**Comment by ghost** [comment]
Ps: you should make some changes for the world

**Comment by ausarneteru** [comment]
Thank you, I think bluhd-lion is preety cool art. I am the creator of it. I will add some more artwork that has more worldly content, I think that is a good suggestion.
